### ISSUE TITLE
Optimize worfklow trigger

### ISSUE THREAD

**Issue by dev-aston** [lajavaness/annotto-api#30]
The current workflow definition makes actions to trigger twice : for the push and the PR
Do you need to run actions for a push that is not yet related to a PR ?

If not, I suggest changing the yml définition with the following : 
```
on:
  pull_request:
  push:
      branches:
        - "main"
        - "next"
```
for **semantic-release job**
```
    if: github.event_name != 'pull_request'
```
for **docker-build-and-push**
```
    if: github.event_name != 'pull_request' && needs.semantic-release.outputs.is-new-version == 'true'
```
